version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    command: sh start.prod.sh
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.23
    env_file:
      - .env
    ports:
        - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres

volumes:
  postgres:
    name: saleshelper-db-volume
  pgadmin:
    name: saleshelper-pgadmin-volume
  