version: "3"

services:
  # main:
  #   container_name: main
  #   build:
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #   command: sh ./startup.sh
  #   env_file:
  #     - .env
  #   networks:
  #     - saleshelper
  #   depends_on:
  #     - pg
  pg:
    container_name: pg
    image: postgres:12
    restart: "always"
    expose:
      - "5433"
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
    networks:
      - saleshelper

networks:
  saleshelper:
volumes:
  pgdata: