version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: nest-api-dev
    command: sh scripts/start.dev.sh
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/api
      - /api/node_modules/

  postgres:
    image: postgres:13
    container_name: postgres-dev
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-dev:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin-dev
    image: dpage/pgadmin4:4.23
    env_file:
      - .env
    ports:
        - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    volumes:
        - pgadmin-dev:/var/lib/pgadmin
    depends_on:
        - postgres

volumes:
  postgres-dev:
    name: saleshelper-db-volume-dev
  pgadmin-dev:
    name: saleshelper-pgadmin-volume-dev
  