version: 2.1

# Define the jobs we want to run for this project
jobs:
  tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test

  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "cd api && docker-compose down && git pull && docker-compose up --build -d -V"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - tests
      - pull-and-build:
          requires:
            - "tests"
          filters:
            branches:
              only:
                - main